### ISSUE TITLE
Jittering in search results in Obsidian 0.8.0

### ISSUE THREAD

**Issue by pivic** [benwf/obsidian-benwf#1]
Using macOS Cataline (10.15.5) with Obsidian insider build v0.8.0 that was released yesterday. When using the global search functionality and scrolling down through the results, the entire pane starts jittering; I've captured this behaviour in a screencast that is embedded on this page: https://snowsoftware.d.pr/yIB0zu

I tried disabling obsidian.css—by renaming it—and the error did not occur. This leads me to believe the error is somehow connected to your theme, even though I'm not sure at all about that...

I also downloaded the two-day old version of obsidian.css from your GitHub repository but there was no difference.

Please let me know if I can help out in any way to resolve this. Thanks!

**Comment by benwf** [comment]
Hey @pivic,

first of all: whoah thanks for using my theme!

Regarding your issue: "of course" I can't reproduce it, but I remember having the same problem a few weeks ago, too, but it simply went away.

For the time being, I'll update the search, there are some other glitches in there, and maybe this fixes it already. I'll have it pushed in an hour or two.

Thanks for letting me know!

**Comment by pivic** [comment]
Hey @benwf!

Thanks for responding! I'm guessing that my issue could very well have *anything* to do with my environment being Mac, or basically anything that could cause this.

Anyway, thanks a lot for reaching out! Looking forward to the new update regardless, I love your theme!

**Comment by benwf** [comment]
Wow, thank you!

Pushing an update now, let me know if this fixed it for you. I'm on a Mac, too (that's why I wanted something like iA Writer), and remember having read something about like this on Discord or the forum as well, but I just can't seem to find it anymore.

**Comment by pivic** [comment]
I think I found a really fringe use case there... I mean, I've downloaded the new version of obsidian.css and the issue remains with that specific search! I've yet to be able to replicate it via any other search. Thanks a lot for being kind and checking this out for me! I'm a very happy user.

**Comment by benwf** [comment]
Of course! If you find anything else or would love to see something, please do let me know!
